version: "3.8"
services:

  app:
    depends_on:
      - database
    container_name: nodejs2023Q2-service-app
    image: amazingsanya/nodejs2023q2-service-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    restart: always
    networks:
      - service_network
    command: npm run docker

  database:
    container_name: nodejs2023Q2-service-database
    image: postgres:15.4-alpine3.18
    restart: always
    environment:
      POSTGRES_DB: $PG_DB_NAME
      POSTGRES_USER: $PG_DB_USERNAME
      POSTGRES_PASSWORD: $PG_DB_PASSWORD
    ports:
      - ${PG_DB_PORT}:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - service_network
    
volumes:
  postgres:

networks:
  service_network: